server:
  port: 8090

spring:
  application:
    name: tennis-score-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: tennis-group
      auto-offset-reset: latest
      enable-auto-commit: false # Manual commits for better control
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: MANUAL_IMMEDIATE # Ensure processing order
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.kafka: INFO
    com.sconde.kata: INFO